[INIT]
Nombre=Winter AO Resurrection
StartPort=7666
LastSockListen=2716
LimiteConexionesPorIp=3
Hide=0
AllowMultiLogins=1
IdleLimit=5
VersionBuildCliente=5.0.28
IniciarDesdeBackUp=0
PuedeCrearPersonajes=1

NivelMaximo=50

ExpMulti=1
OroMulti=1
OficioMulti=5
DropItemsAlMorir=1
ArtesaniaCosto=50000

CentinelaAuditoriaTrabajoActivo=1

ContadorAntiPiquete=15
MinutosCarcelPiquete=10

ServerSoloGMs=0
Testing=0

ArmaduraImperial1=370
TunicaMagoImperial=517
TunicaMagoImperialEnanos=549
ArmaduraImperial2=372
ArmaduraImperial3=492

ArmaduraCaos1=379
TunicaMagoCaos=518
TunicaMagoCaosEnanos=558
ArmaduraCaos2=523
ArmaduraCaos3=383
VestimentaImperialHumano=675
VestimentaImperialEnano=676
TunicaConspicuaHumano=679
TunicaConspicuaEnano=682
ArmaduraNobilisimaHumano=629
ArmaduraNobilisimaEnano=681
ArmaduraGranSacerdote=680

VestimentaLegionHumano=677
VestimentaLegionEnano=678
TunicaLobregaHumano=683
TunicaLobregaEnano=685
TunicaEgregiaHumano=634
TunicaEgregiaEnano=686
SacerdoteDemoniaco=684

MaxUsers=550

Record= 4

Admines=2
Dioses=3
SemiDioses=0
Consejeros=1
RolesMasters=1

[Admines]
Admin1=Lorwik
Admin2=Zharkel

[Dioses]
Dios1=Howell
Dios2=Santo
Dios3=Estalagmita

[SemiDioses]
SemiDios1=

[Consejeros]
Consejero1=Jopi

[RolesMasters]
RM1=HollyLight

[CLAN-PRETORIANO]
Mapa=123
X=50
Y=62

[DIFICULTAD]
DificultadExtraer=4

[TIMERS]
IntervaloPuedeSerAtacado=5000
IntervaloAtacable=60000
IntervaloOwnedNpc=18000

[INTERVALOS]
SanaIntervaloSinDescansar= 1600
StaminaIntervaloSinDescansar= 10
StaminaIntervaloLloviendo= 110
SanaIntervaloDescansar= 100
StaminaIntervaloDescansar= 5
IntervaloSed= 3000
IntervaloHambre= 3500
IntervaloVeneno= 500
IntervaloIncinerado= 400
IntervaloParalizado= 500
IntervaloInvisible= 500
IntervaloOculto=500
IntervaloFrio=15
IntervaloWAVFX=190
IntervaloNpcPuedeAtacar=3000
IntervaloTrabajo=1200
IntervaloWS=180 'Cantidad de minutos
IntervaloInvocacion= 1001
IntervaloPerdidaStaminaLluvia=9999
IntervaloParaConexion= 3000
IntervaloTimerExec=50
IntervaloCerrarConexion=10 'Segundos
IntervaloReconexionDB=360 'Minutos
IntervaloAutoReiniciar=100000 '-1 para deshabilitar
IntervaloGuardarUsuarios=180

IntervaloUserPuedeAtacar= 1400
IntervaloLanzaHechizo= 810
IntervaloUserPuedeUsar=250
IntervaloFlechasCazadores=900
IntervaloMagiaGolpe=580
IntervaloGolpeMagia=580
IntervaloGolpeUsar=300
IntervaloGlobal=5000
IntervaloMakreo=23

'Aqui se pueden poner estadisticas customizadas para cuando un Personaje nace.
'Opcion Activado=1 para poder hacer uso del mismo, caso contrario se usan las estadisticas por defecto
'Se puede customizar absolutamente todo, hay parametros que no pueden superar el valor aqui mostrado
'Caso contrario pueden encontrar el juego puede dejar de funcionar.
[ESTADISTICASINICIALESPJ]
Activado=0
Nivel=50 'MAX 255
SkillPoints=100 'MAX 255
Oro=21474836 'MAX 2147483647
Banco=21474836 'MAX 2147483647

[CONEXIONAPI]
Activado=1
UrlServer=http://localhost:1337
ApiPath=C:\Users\Administrator\Desktop\alkon\ao-api-server

# DSN es un parametro OPCIONAL. Si no sabes lo que es, no lo completes.
# Si te conectas a la DB via DSN, no hace falta completar los otros campos. (Host, Name, Username, Password)
[DATABASE]
DSN=
Host=192.168.1.5
Name=winterao
Username=winterlocal
Password=lwkestamamadisimo20local

[HAPPYHOUR]
Activado=0
## Formato: Hora-% (la hora es de 0 a 23hs) (el % es convertido x100, 1 el doble de exp)
Dia1=20-4	## Lunes
Dia2=20-3
Dia3=20-3
Dia4=19-4
Dia5=19-3
Dia6=19-3
Dia7=18-3	## Domingo

