# DSN es un parametro OPCIONAL. Si no sabes lo que es, no lo completes.
# Si te conectas a la DB via DSN, no hace falta completar los otros campos. (Host, Name, Username, Password)
# MySQL ODBC 8.0 ANSI Driver
[USER_DATABASE]
DSN=
Host=127.0.0.1
Name=winterao
Username=root
Password=neosone789

[ACC_DATABASE]
DSN=
Host=127.0.0.1
Name=winterweb
Username=root
Password=neosone789