# DSN es un parametro OPCIONAL. Si no sabes lo que es, no lo completes.
# Si te conectas a la DB via DSN, no hace falta completar los otros campos. (Host, Name, Username, Password)
# MySQL ODBC 8.0 ANSI Driver
[USER_DATABASE]
DSN=
Host=192.168.1.12
Name=winterao
Username=winterlocal
Password=lwkestamamadisimo20local

# [ACC_DATABASE]
# DSN=
# Host=192.168.1.12
# Name=comunidadwinter
# Username=comunid4_comaccwinter
# Password=BY9woN1o?[4APfz*Fb

[ACC_DATABASE]
DSN=
Host=192.168.1.12
Name=winterweb
Username=kiwrolwinter
Password=G79XNDLMofdZcRVO