# DSN es un parametro OPCIONAL. Si no sabes lo que es, no lo completes.
# Si te conectas a la DB via DSN, no hace falta completar los otros campos. (Host, Name, Username, Password)
[USER_DATABASE]
DSN=
Host=192.168.1.5
Name=winterao
Username=winterlocal
Password=lwkestamamadisimo20local

[ACC_DATABASE]
DSN=
Host=172.104.4.154
Name=comunid4_accountwinter
Username=comunid4_comaccwinter
Password=BY9woN1o?[4APfz*Fb